[build]
  functions = "netlify-functions"   # Path to functions directory
  publish = "dist"  # Folder to publish after build

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
